### ISSUE TITLE
Error Help : Is this project still active?

### ISSUE THREAD

**Issue by keniel123** [lanthaon/sl-animation-blender#10]
I am receiving the following error when I run load_mp_landmarks.py

Python: Traceback (most recent call last):
  File "/load_mp_landmarks.py", line 395, in <module>
  File "/load_mp_landmarks.py", line 331, in create_bones
  File "/Applications/Blender.app/Contents/Resources/4.1/scripts/modules/bpy/ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Operator bpy.ops.object.posemode_toggle.poll() Context missing active object

**Comment by mgranchelli** [comment]
I've the same error. Any solution?
